
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [6]:
import numpy as np
Array = np.arange(1,10)
print(Array)

[1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [5]:
Array = np.arange(9)
Reshaped_Array = array.reshape(3, 3)
print(Reshaped_Array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [7]:
array = np.arange(9).reshape(3, 3)
Chosen_One = array[1, 1]
print(Chosen_One)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [11]:
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
Addition = np.add(Array1, Array2)
print(Addition)
Subtraction = np.subtract(Array1, Array2)
print(Subtraction)
Multiplication = np.multiply(Array1, Array2)
print(Multiplication)
Division = np.divide(Array1, Array2)
print(Division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [12]:
Array = np.array([1, 2, 3, 4, 5])
Sum_Array = np.sum(Array)
print(Sum_Array)
Mean_Array = np.mean(Array)
print(Mean_Array)
Std_Array = np.std(Array)
print(Std_Array)

15
3.0
1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [13]:
Array = np.array([1, 2, 3, 4, 5, 6])
Reshaped_array = Array.reshape((2, 3))

print(Reshaped_Array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [15]:
Array = np.random.randint(low=0, high=10, size=(5, 5))

print(Array)

[[2 4 8 4 2]
 [3 4 3 9 4]
 [2 4 8 7 1]
 [2 2 7 8 5]
 [2 0 2 4 5]]


Replace all values in the sub-array with a specific value.


In [16]:
Row_Start, Row_End = 1, 3
Col_Start, Col_End = 2, 4

Array[Row_Start:Row_End, Col_Start:Col_End] = 10

print(Array)

[[ 2  4  8  4  2]
 [ 3  4 10 10  4]
 [ 2  4 10 10  1]
 [ 2  2  7  8  5]
 [ 2  0  2  4  5]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [17]:
Array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
Sub_Array = Array[[1, 3], :]
print(Sub_Array)

[[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [18]:
Array = np.array(np.arange(3)*3 + np.arange(3)[:, None], dtype=int)
print(Array)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [19]:
Array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Array_1d = np.array([10, 11, 12])
Result = Array_2d + Array_1d[:, np.newaxis]

print(Result)

[[11 12 13]
 [15 16 17]
 [19 20 21]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [20]:
Array1 = np.random.randint(0, 10, size=(3, 3))
Array2 = np.random.randint(0, 10, size=(3, 3))

print("Array 1:")
print(Array1)
print("Array 2:")
print(Array2)

Array 1:
[[4 9 3]
 [3 5 8]
 [6 0 7]]
Array 2:
[[7 1 5]
 [1 9 3]
 [8 0 7]]


In [22]:
Array_h = np.concatenate((Array1, Array2), axis=1)
Array_v = np.concatenate((Array1, Array2), axis=0)

print("Horizontally:")
print(Array_h)
print("Vertically:")
print(Array_v)

Horizontally:
[[4 9 3 7 1 5]
 [3 5 8 1 9 3]
 [6 0 7 8 0 7]]
Vertically:
[[4 9 3]
 [3 5 8]
 [6 0 7]
 [7 1 5]
 [1 9 3]
 [8 0 7]]


In [24]:
Array_v = np.concatenate((Array1, Array2), axis=0)
Array1_v, Array2_v = np.vsplit(Array_v, 2)

print("Original Vertical:")
print(Array1_v)
print("Original Vertical):")
print(Array2_v)

Original Vertical:
[[4 9 3]
 [3 5 8]
 [6 0 7]]
Original Vertical):
[[7 1 5]
 [1 9 3]
 [8 0 7]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [28]:
Array = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Count_Dict = {}

Mode = None
Max_Count = 0
for Element in Array:
    if Element not in Count_Dict:
        Count_Dict[Element] = 1
    else:
        Count_Dict[Element] += 1
for Element, Count in Count_Dict.items():
    if Count > Max_Count:
        Mode = Element
        Max_Count = Count
    elif Count == Max_Count:
        Mode = [Element, Mode]

print("Mode: ", Mode)

Mode:  1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

